# Generated by Django 5.2.12 on 2026-04-06 07:00

import candidates.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(help_text='PDF only, max 10MB', upload_to=candidates.models.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('scored', 'Scored'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='processing', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(limit_choices_to={'role': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
        migrations.CreateModel(
            name='CVText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfminer_text', models.TextField(blank=True, default='')),
                ('pymupdf_text', models.TextField(blank=True, default='')),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('best_text', models.TextField(blank=True, default='')),
                ('extraction_method', models.CharField(blank=True, default='', max_length=20)),
                ('skills_extracted', models.JSONField(blank=True, default=list)),
                ('education_extracted', models.JSONField(blank=True, default=list)),
                ('experience_years', models.FloatField(default=0)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_text', to='candidates.application')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_req_score', models.FloatField(default=0, help_text='0-100 percentage')),
                ('hard_req_passed', models.BooleanField(default=False)),
                ('hard_req_details', models.JSONField(blank=True, default=dict, help_text='Per-requirement match details')),
                ('logistic_regression_score', models.FloatField(default=0)),
                ('naive_bayes_score', models.FloatField(default=0)),
                ('knn_score', models.FloatField(default=0)),
                ('decision_tree_score', models.FloatField(default=0)),
                ('random_forest_score', models.FloatField(default=0)),
                ('svm_score', models.FloatField(default=0)),
                ('xgboost_score', models.FloatField(default=0)),
                ('autogluon_score', models.FloatField(default=0)),
                ('ensemble_score', models.FloatField(default=0, help_text='Weighted average 0-100')),
                ('overall_score', models.FloatField(default=0, help_text='Final combined score 0-100')),
                ('label', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10)),
                ('shap_explanation', models.JSONField(blank=True, default=dict, help_text='Feature importance + positive/negative factors')),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='candidates.application')),
            ],
            options={
                'ordering': ['-overall_score'],
            },
        ),
    ]
